server:
  port: 9021

spring:
  main:
    allow-circular-references: true
  application:
    name: UMS-MEETING-SERVICE
  datasource:
    driver-class-name: org.postgresql.Driver
    password: manager
    url: jdbc:postgresql://localhost:5432/umsmeetingdb
    username: postgres
  devtools:
    restart:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    password: qshd bgwz wurs pivv
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
    username: vaishnavdev05@gmail.com