server:
  port: 9021

logging.level:
  '[org.hibernate.sql]': DEBUG
  '[org.hibernate.type]': TRACE
spring:
  main:
    allow-circular-references: true
  application:
    name: UMS-MEETING-SERVICE
  datasource:
    driver-class-name: org.postgresql.Driver
    password: manager
    url: jdbc:postgresql://localhost:5432/umsmeetingdb
    username: postgres
  devtools:
    restart:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
  mail:
    host: smtp.gmail.com
    password: fceu fdef cxwh dzpi
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
    username: umsassist@gmail.com